### ISSUE TITLE
[WFRP4e System] Problem with an actor sheet

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#101]
When I try to add some spell in my character sheet i've the following message : 

"Something went wrong with preparing item The Caress Of Laniph SyntaxTypeError : Unexpected indentifier "<br/>**From**: Sneeq’ Skaul#8973 (discord)<br/>wfrp4e: 3.0.0<br/>wfrp4e-core: 1.0

**Comment by guillaumecd15** [comment]
I ve the same issue for other spells

**Comment by moo-man** [comment]
I can't seem to reproduce this error. Does it also happen with new actors?

**Comment by guillaumecd15** [comment]
HiI am able to avoir the issue when i use the module that translate Warhammer in frenchhttps://gitlab.com/LeRatierBretonnien/foundryvtt-wh4-lang-fr-fr if i unselect it, and keep the core game in french, i do not get the issue anymoreWhen i change the core game to french, the issue appears      De : RussellEnvoyé le :samedi 7 novembre 2020 03:09À : moo-man/WFRP4e-FoundryVTTCc : guillaumecd15; CommentObjet :Re: [moo-man/WFRP4e-FoundryVTT] [WFRP4e System] Problem with an actor sheet (#101) I can't seem to reproduce this error. Does it also happen with new actors?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
