### ISSUE TITLE
[Feature request] Add option to Collapse items be worn

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1527]
Can you consider add option to Collapse items, that they can be worn (also view that they are worn or not) without use expand button, check worn and then collapse again.

Current:
![obraz](https://user-images.githubusercontent.com/99994770/230911833-1e6a7ce6-177c-4a69-89e1-2077559934c3.png)

Suggested (see Clothing and Accessories): 
![Bez nazwy-1](https://user-images.githubusercontent.com/99994770/230913586-a8e47749-ee0e-44cb-8187-0cb040a3059e.png)

**Comment by Forien** [comment]
I have an alternative suggestion, since collapsing view's purpose is to save space, I think we could so an indicator within the icon itself.

My proposal is something like this (two versions presented on the runic daggers):

![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/2d967bb5-2956-48b7-95f0-140ff4fb51e9)

The idea is that "visible indicator means it's worn/equipped" and **toggling would happen with right-mouse click**. Thoughts @GregorHak @moo-man ?

Alternatively every item could have an indicator, but worn/equipped would be filled with another shape/icon. And we could do that clicking the indicator would toggle the state of the item.

**Comment by moo-man** [comment]
I'm not sure, the original suggestion was straightforward, sure it takes an extra row of space, but the UI is much clearer (a lot of people will miss right click toggle and assume you can't modify it)
