### ISSUE TITLE
[WFRP4e System] Opposed tests with combat targeting have static defender results

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1703]
Hi, 
I don't think the opposed rolls when using combat targeting are working as intended.

If Player A targets Player B and initiates a melee attack then both should be making Weapon Skill test against their current level to work out Successes or Failures. Then those levels are compared to see who wins. But when I take a look at the console it appears as though the OpposedTest.data.defenderTestData.result.roll always equals 0 and the defenders other results never change from their starting value of 0 apart from the target value.

It looks as though the defender is stuck with a default value of 0 and the combat is decided purely on the attackers roll. If they succeed then their success levels are added to their damage. But if they fail then the defender is assigned their failure levels as successes as if they rolled something.

There are three main problems with this approach:
[1] The victor is meant to be decided by the highest number of success/failure levels. Both players can fail to roll under their skill but there still has to be a winner .  Right now the victor is only decided by the attacker.
[2] The defender has an opportunity to Crit/Fumble on their roll too making combat more dangerous. With no roll taking place this is impossible.
[3] The defender has no way of selecting another skill to defend with other than WS which is automatically selected. 

NOTE: I've tested this using the manual process of first rolling one characters attack without targeting, then clicking the "opposed test" button in the chat box, and then rolling an opposed test separately without targeting. This is working as intended.<br/>**From**: heretek_sec<br/>foundry: 11.305<br/>wfrp4e: 6.5.9<br/>wfrp4e-altdorf: 3.0.0<br/>wfrp4e-archives1: 3.0.2<br/>wfrp4e-archives2: 3.0.6<br/>wfrp4e-core: 3.1.4<br/>wfrp4e-dotr: 3.0.4<br/>wfrp4e-eis: 3.1.6<br/>wfrp4e-empire-ruins: 3.0.8<br/>wfrp4e-horned-rat: 2.0.1<br/>wfrp4e-middenheim: 3.0.2<br/>wfrp4e-pbtt: 3.0.1<br/>wfrp4e-rnhd: 3.0.7<br/>wfrp4e-starter-set: 3.1.5<br/>wfrp4e-ua1: 3.0.2<br/>wfrp4e-ua2: 2.0.0<br/>wfrp4e-up-in-arms: 3.0.6<br/>wfrp4e-wom: 3.0.5<br/>wfrp4e-zoo: 3.0.2<br/>Active Modules: dice-so-nice, drag-ruler, image-hover, socketlib, tabletop-rpg-music, wfrp4-wfrp4e-npc-generator, wfrp4e-gm-toolkit, wfrp4e-random-treasure, wfrp4e-unofficial-grimoire

**Comment by Forien** [comment]
Not sure if I undesratnd the issue here, but I assume you expected system to perform an automatic roll for the defender. It doesn't.  
System _never_ rolls automatically _for_ the Players. Defending Player **_has to_** perform his/her own roll. Main reason is that defender sometimes can't defend themselves, or can oppose with _different_ skill. You can use `Dodge` skill to oppose a `Melee` skill. You can oppose `Intimidate` skill using `Cool` skill. It's all fluid and is often decided by the Player or the GM on the spot, so system can't (and should not!) autoroll. 

If system would autoroll for players, it would take away their agency over their characters and/or actions.



How combat works for me:


## Setup
Eloise and Konrat stand next to each other, Eloise has a Dagger and Konrat has a Zweihander  

![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/5aabd2a2-aa61-48ea-a676-6fa33eb50c91)


## Eloise's Turn
Eloise attacks using Dagger:

![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/0875afe9-68e2-49c4-bc24-e9fbff064788)

![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/dfbad4d9-cb95-481c-a5a4-3027b7bedc93)


## Konrat's response to the attack

Then Konrat has an option to do one of 3 things:
1. Defend with Zweihander (Oppose with Melee (Two-Handed) using Zweihander)
2. Dodge (Oppose with Dodge skill)
3. Not oppose (attack is unopposed).

Konrat chooses to defend with his weapon: 

![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/8d8ec636-bad3-4643-ab0e-35d7a6c900c6)

## Opposed Test result

![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/9b57045d-fd37-46c6-bd62-b19203d1f52f)

Opposed Test is properly calculated. `-4 SL` of Eloise and `+7 SL` from Konrat results in Konrat winning the Opposed Test by `11 SL`.   
Additionally weapon's reach is taken into account, because I enabled that in settings.

**Comment by moo-man** [comment]
User wasn't aware of the opposed process, thanks @Forien for the walkthrough

**Comment by GregorHak** [comment]
nice walkthrough, maybe paste it here: https://github.com/moo-man/WFRP4e-FoundryVTT/wiki/Combat
