### ISSUE TITLE
[Core Rulebook] Talents such as Attractive do not trigger on results ending with "0"

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1831]
When looikng at the units dice value, talents such as Attractive do not account for "0" being counted as "10" for purposes of SL.

Something along the following lines is needed:

if (ones === 0) {ones = 10}

The following talents are affected:

Argumentative
Attractive
Cardsharp
Diceman
Supportive<br/>**From**: thefirst5<br/>foundry: 11.313<br/>wfrp4e: 7.0.3<br/>wfrp4e-altdorf: 4.0.1<br/>wfrp4e-archives1: 4.0.2<br/>wfrp4e-archives2: 4.0.2<br/>wfrp4e-core: 4.0.2<br/>wfrp4e-dotr: 4.0.2<br/>wfrp4e-eis: 4.0.1<br/>wfrp4e-horned-rat: 4.0.2<br/>wfrp4e-middenheim: 4.0.2<br/>wfrp4e-pbtt: 4.0.2<br/>wfrp4e-rnhd: 4.0.1<br/>wfrp4e-up-in-arms: 4.0.1<br/>wfrp4e-wom: 4.0.1<br/>Active Modules: about-face, dd-import, drag-ruler, easy-target, fast-flip, forien-armoury, foundryvtt-simple-calendar, fxmaster, lib-wrapper, popout, quick-insert, smalltime, socketlib, stairways, times-up, token-action-hud-core, token-action-hud-wfrp4e, token-z, tokenmagic, wfrp4e-gm-toolkit, forge-vtt

**Comment by Forien** [comment]
I mean, 0 is 0. It's not 10. You get 0-9 SL from these talents. 

When you roll d100, you do not perform two d10 rolls with range of 1-10, you perform one roll with two dice where one die represents tens (0-9) and the other die represents units (0-9), where result `00` represents `100`. 

CRB, page 6.

**Comment by TheFirst05** [comment]
I don't think I follow. CRB page 6 states: "ten-sided dice are typically marked from 0–9, where a roll of 0 counts as a result of 10"

Attractive states: "you can choose to either use your rolled SL, or the number rolled on your units die." 

So a roll of a 0 on the units die counts as a 10.

It's the same reason why Damaging goes from 1-10, not 0-9 (in the Foundry system, at least), and having 0 sin points doesn't trigger Wrath of the Gods.

**Comment by Forien** [comment]
> I don't think I follow. CRB page 6 states: "ten-sided dice are typically marked from 0–9, where a roll of 0 counts as a result of 10"
> 
> Attractive states: "you can choose to either use your rolled SL, or the number rolled on your units die."
> 
> So a roll of a 0 on the units die counts as a 10.
> 
> It's the same reason why Damaging goes from 1-10, not 0-9 (in the Foundry system, at least), and having 0 sin points doesn't trigger Wrath of the Gods.

It first describes `d10` rolls. It even literally says `these dice are called d10s in the rules,`. It **does not describe the d100**. It does it in the latter paragraph, where it states " to do this, one ten-sided die is designated as a ‘tens’ die, and the other as the ‘units’ die. now roll the two dice, and read the result as a **two-digit** number."

If for d100 you would roll two d10s (so treat them as 1-10), then multiply one by 10 (tens) and add them together, then you would be unable to rull results below 10 and you would be able to roll results above 100. Because your range would be 10-109. Because no matter which die you would roll "0", it would mean "10". 

Also consider rules that tell you to "reverse" the d100 roll. If 0 on unit die is 10, then d100 result of 10 after reversing would still be 10? No, it wouldn't, because 0 is not 10.

Damaging also should result in 0-9 acording to CRB. And I thought it does. If it doesn't, then I don't know why, but I do personally dislike it.

**Comment by moo-man** [comment]
> then I don't know why

Because, well, that's how the developers said it worked. I originally also thought Damaging/Sin Points didn't count as 10 when the units die was 0, because that makes more sense to me.

**Comment by Forien** [comment]
> > then I don't know why
> 
> Because, well, that's how the developers said it worked. I originally also thought Damaging/Sin Points didn't count as 10 when the units die was 0, because that makes more sense to me.

I thought you don't count Andy Law's post-mortem rule changes as RAI? Or was it official C7 post?

**Comment by moo-man** [comment]
Well, this was before the system was made, I came into it knowing what the developers intended for this, I believe.

It's also a case where, for this rule (particularly Damaging, which is very common), there would constantly be questions about it if I went back.

**Comment by Forien** [comment]
> Well, this was before the system was made, I came into it knowing what the developers intended for this, I believe.
> 
> It's also a case where, for this rule (particularly Damaging, which is very common), there would constantly be questions about it if I went back.

I would suggest making it a "homerule" setting then, with ability to not use it. If you made it enabled by default, current users wouldn't ask.
And then the homerule could affest the talents that OP mentioned. Consistency is great and I prefer consistency above all, sure, but still would be nice to use CRB rules.

If you agree but are too busy, I could implement it

**Comment by TheFirst05** [comment]
I think there might be some contention on which one is the houserule ;) But unfortunately such is the way with wfrp4e.

Regardless, consistency is the important bit. It seems to be a very simple switch.

**Comment by Forien** [comment]
> I think there might be some contention on which one is the houserule ;) But unfortunately such is the way with wfrp4e.
> 
> Regardless, consistency is the important bit. It seems to be a very simple switch.

Personally, anything that's not RAW is a homerule/houserule. Even if it makes more sense (like one helmet that does nothing). 

RAI is perhaps a grey area, but I still think it would count as houserule, because since it's not RAW, it requires at least some additional research to "learn" that rule. and someone who only read CRB and Errata will not know that and could possibly get confused. 

Don't get me wrong, many houserules are great and make perfect sense (looking at you, Open Helm), but if it's not directly coming from written rules in official CRB, then I believe it should count as houserule. 

I'm also not saying that counting `0` results for these talents (and Damaging) is bad or something, just that I strongly believe it's  a houserule/unofficial RAI. And I _personally_ would prefer to play without it, that's all :)
