### ISSUE TITLE
[WFRP4e System] Critical Wound Cap Inaccurate 

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1861]
Ive had a few players make characters recently and it seems there character sheet puts there critical wound cap at 0/2 regardless of what their toughness bonus comes out to be. Changing the toughness bonus doesn’t seem to bring a change in results but it does for corruption and wounds. Easy to fix randomly but im sure you'd like to be aware on the bug. Cheers!<br/>**From**: playbenjiplay<br/>foundry: 11.315<br/>wfrp4e: 7.0.3<br/>wfrp4e-altdorf: 4.0.1<br/>wfrp4e-archives1: 4.0.2<br/>wfrp4e-archives2: 4.0.2<br/>wfrp4e-core: 4.0.2<br/>wfrp4e-eis: 4.0.1<br/>wfrp4e-middenheim: 4.0.2<br/>wfrp4e-owb1: 4.0.2<br/>wfrp4e-rnhd: 4.0.1<br/>wfrp4e-ua1: 4.0.1<br/>wfrp4e-ua2: 4.0.2<br/>wfrp4e-up-in-arms: 4.0.1<br/>wfrp4e-wom: 4.0.1<br/>wfrp4e-zoo: 4.0.1<br/>Active Modules: baileywiki-cabal-dungeon, baileywiki-city-district-01, baileywiki-city-district-02-docks, baileywiki-city-district-03-temples, baileywiki-city-district-04-ruins-and-slums, baileywiki-city-district-05-affluent, baileywiki-maps-premium, baileywiki-maps-premium-towns, baileywiki-nuts-and-bolts, betterroofs, combat-tracker-dock, compendium-folders, dice-so-nice, dungeon-draw, fxmaster, levels, lib-wrapper, monks-active-tiles, monks-tokenbar, moulinette-core, moulinette-gameicons, moulinette-imagesearch, moulinette-scenes, moulinette-sounds, moulinette-tiles, multiface-tiles, scene-packer, tagger, tile-scroll, token-attacher, tokenmagic, vtta-tokenizer, wall-height, wfrp4e-gm-toolkit, forge-vtt

**Comment by Forien** [comment]
Can you check if the character sheet have enabled automated Critical Wound calculations? Because if you can "fix" it (change number manually), then I am pretty sure that you (or your player) disabled it. 
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/223a1fc5-55ac-4df5-b795-a6b1fc2f3c98)


If it's enabled and you still don't get automated critical wound calculations done, then something is wrong. Can you check console (F12 on chromium browsers) for errors? Best to first open console, then refresh the world (F5), wait till it load, open the character sheet and then look in console. 

If there will be no errors, then of course you should check if it still happens with all unofficial modules disabled.

**Comment by moo-man** [comment]
Actor had Auto-calculate Critical Wounds off
