### ISSUE TITLE
[Core Rulebook] Issues with Miracle Soulfire

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1911]
Having the following issues with  Miracle Soulfire
   -Can not increase AoE
   -Template Radius is 1/2 of expected i.e. Fellowship Bounus = 3 Template Distance (radius) = 1.5 not 3<br/>**From**: steven.evans<br/>foundry: 11.315<br/>wfrp4e: 7.0.3<br/>wfrp4e-core: 4.0.2<br/>Active Modules: custom-css, drag-ruler, fuzzy-foundry, improved-macro-editor, module-credits, socketlib, wfrp4e-helper

**Comment by Forien** [comment]
It's probably because it's uses the same reasoning that's for Spell's AoE
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/ddf6923e-ef59-4ade-8b1d-fe8db61a1081)

but yes, the miracle in question seems to be different, as it's an aura from caster, so instead of diameter it should be radius. 

Not sure if it's easy to change in the system, maybe upcoming effect refactor will fix that.

---
Anyway, for now the solution on user end would be to double the AoE (so instead of `Fellowship Bonus` set it to `Fellowship Bonus * 2`)

**Comment by StevenEvans1966** [comment]
first issue is from this line  in ParyTest seam a redundate test to me. 
 async _overcast(choice) {
    if (this.result.overcast.usage[choice].AoE) {
      ui.notifications.error(game.i18n.localize("ERROR.PrayerAoEOvercast"));
    } else {
      await super._overcast(choice);
    }
  }
```

**Comment by StevenEvans1966** [comment]
second issue 
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/81326195/1e2baf65-0d76-4fe4-9601-03e04b61d1ac)
is setup above says radius adding *2 not a problem is a code smell

**Comment by moo-man** [comment]
Duplicate #1190
