### ISSUE TITLE
Issue with character sheet updates.

### ISSUE THREAD

**Issue by Kirisaki-Tumet** [moo-man/WFRP4e-FoundryVTT#1937]
When making changes to actor's sheet if multiple people have it open the saving of changes is inconsistent. Making a change wont show on other people screens and the sheet saves in the state of who ever closed the sheet last. Changing the quantity of trappings does change in real time for all views but things like ambition or attribute changes don't show.

**Version Numbers**
7.1.2 on foundry Version 11 build 315

Foundry:
We disabled all modules expect the core modules for books content.

**Comment by moo-man** [comment]
This isn't something within the scope of the system, this is just how Foundry form submission works. Sheets are not meant to be fully collaborative.

**Comment by Forien** [comment]
@moo-man I think the issue here is that change is not propagating properly. Like, if one person makes a change, its not saved (or at least not updated properly) and not visible to others.
Discussion:  https://discord.com/channels/449845411344154634/712500603250802829/1233768531816874115

**Comment by Forien** [comment]
Pains me to comment on it again, however... 
I tested it on newest codebase, since I had issues with Group Advantages (see #1945 ) and it turns out there are some serious desyncing problems and update problems. 

It's very extreme and at this point borderline unusable. It used to only hit Max Critical Wounds pre 7.1 (if player was doing anything on their Actor, GM always saw Max Critical Wounds as 2, but players saw it correctly and it was working correctly, if players were not connected and GM refreshed, GM saw correct value), but now it breaks the whole Sheet :( 

---

GM (native app) on the left, player (chrome) on the right:
https://i.gyazo.com/0833d36c43e44d4cdc2fd3c9b6efa488.mp4

1. Notice how things are not updating across users
2. Notice how things sometimes revert on the same user end
3. Notice how Critical Wounds somehow disappear on GM view (only if player is connected, this is actually old bug)

I have tried to find out the reason of it, but I couldn't even think where to start looking...
