### ISSUE TITLE
[WFRP4e System] cannot roll profesion

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2160]
some issues rise when I tried to create character<br/>**From**: dziobakroll1d12<br/>foundry: 12.329<br/>wfrp4e: 7.2.4<br/>Active Modules:

**Comment by Forien** [comment]
1. It's usually better to provide some information and insight as to what "issues" are. Nobody can read your mind or see your screen or guess what your problem is if you do not explain/describe it.
2. Character Generation requires you to either have `WFRP4e Core` Module enabled, or you need to create Career Items and Rolltables yourself.

**Comment by moo-man** [comment]
Yeah, closing this due to lack of details, but it's probably because the core module isn't enabled
