### ISSUE TITLE
[WFRP4e System] Impact and Tiring weapons on opposed tests

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#220]
Ran an opposed test:
- No charging, with a Great Axe that has Impact, Hack, and Tiring qualities.
- Won the opposed test, roll of 50 vs 110 vs roll of 10 vs 60

Damage should be: 
SL = +6 - +5 = 1
Damage = SB + 6 = 4 +6 = 10
Total damage = 11

Damage calculated: 21
My guess:
- Added Impact damage when Tiring should have cancelled it
- Added 10 damage from impact on a roll of 50, which should add 0 instead.

When changing initial roll to 51 vs 110, damage calculated was 12.
<br/>**From**: @Nelson on Discord<br/>wfrp4e: 3.2.0<br/>wfrp4e-core: 1.0<br/>wfrp4e-eis: 1.01<br/>wfrp4e-rnhd: 1.03<br/>wfrp4e-starter-set: 1.03

**Comment by siegn** [comment]
Example for roll of 50
![image](https://user-images.githubusercontent.com/37192527/99891597-9042ff80-2c39-11eb-8a96-a3eb90914368.png)
Example for roll of 51
![image](https://user-images.githubusercontent.com/37192527/99891600-9cc75800-2c39-11eb-85b9-e61753ac3f4e.png)

As discussed in discord, looks like I was wrong about the 50 should add 0, so ignore that part.
Also, I am sorry about the module version, I thought I had updated them all. I have now updated wfrp4e-core to v1.11 and can confirm the issue is still there.
