### ISSUE TITLE
[WFRP4e System] Auras are rendered even when disabled

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2202]
I have an Aura Active Effect with disabled "Render Aura" setting, yet aura is still rendered around the token.

<br/>**From**: forien<br/>foundry: 12.331<br/>wfrp4e: 8.0.2<br/>wfrp4e-altdorf: 6.0.0<br/>wfrp4e-archives1: 6.0.0<br/>wfrp4e-archives2: 6.0.0<br/>wfrp4e-core: 6.0.0<br/>wfrp4e-dotr: 6.0.0<br/>wfrp4e-eis: 6.0.0<br/>wfrp4e-middenheim: 6.0.0<br/>wfrp4e-owb2: 6.0.0<br/>wfrp4e-pbtt: 6.0.0<br/>wfrp4e-rnhd: 6.0.0<br/>wfrp4e-salzenmund: 6.0.0<br/>wfrp4e-soc: 6.0.0<br/>wfrp4e-starter-set: 6.0.0<br/>wfrp4e-up-in-arms: 6.0.0<br/>wfrp4e-wom: 6.0.0<br/>wfrp4e-zoo: 6.0.0<br/>Active Modules: ATL, JB2A_DnD5e, _CodeMirror, _chatcommands, autoanimations, chat-commander-wfrp4e, colorsettings, custom-css, darkraven-games-soundscapes-free, dfreds-chat-pins, dfreds-effects-panel, dice-so-nice, drag-ruler, entice-with-dice-so-nice, forien-actors-summary, forien-ammo-swapper, forien-armoury, forien-copy-environment, forien-custom-utility, forien-easy-polls, forien-quest-log, forien-unidentified-items, foundryvtt-simple-calendar, image-hover, item-piles, ivan-duch-music-packs, levels, lib-wrapper, light-switch, local-shared-compendiums, michaelghelfi, monks-hotbar-expansion, moulinette-core, moulinette-imagesearch, moulinette-scenes, moulinette-tiles, multi-token-edit, permission_viewer, polyglot, popout, quick-insert, remote-highlight-ui, sequencer, socketlib, soundfxlibrary, stairways, sweetnothings, tabletop-rpg-music, times-up, token-action-hud-core, token-action-hud-wfrp4e, token-ease, token-variants, token-z, trs-foundryvtt-dice-set, trs-metal-rainbow, update-your-password, wall-height, warhammer-lib, wfrp4e-dotr-maps, wfrp4e-gm-toolkit

**Comment by Forien** [comment]
Since it's similar issue and also connected to Library:

WFRP 8.0.2, castle wittgenstein map. Organs don't show distracting Aura. I think there are supposed to be more with auras on the map other than Organs.

Error in console: 
![image](https://github.com/user-attachments/assets/cdfb074f-b477-47b9-bc3c-fd4ebd3a6fd9)
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'center')
[Detected 1 package: warhammer-lib(1.0.1)]
    at AreaTemplate.fromAuraEffect (warhammer.js:2640:29)
    at async Promise.all (index 0)
    at async TokenHelpers.updateAuras (warhammer.js:3326:37)
```

Got the Aura to display after deleting the Trait and readding it. And I cannot seem to reproduce the error message, but I guess it's worth investigating

**Comment by moo-man** [comment]
Are they being rendered but hidden? Because that's intended

**Comment by Forien** [comment]
> Are they being rendered but hidden? Because that's intended

Could be, but if I unhide the token, Aura does not render, even if I disable/enable the effect. Did not test changing scenes though.

As for my initial issue that I reported, it's for my custom `Suffuse with Shyish` Aura (because it still doesn't have one natively). I specifically don't want aura to be rendered, because it's on a familiar that always is next to a party and it clutters scene.
