### ISSUE TITLE
Tables not showing up in Rollable Tables

### ISSUE THREAD

**Issue by gravagehulk** [moo-man/WFRP4e-FoundryVTT#336]
I know we can call up the available Tables by typing /tables in chat and I know a lot of those tables pop up automatically on tests, but I was just curious as to why they don't show in the Rollable Tables. It seems like tables like the Events Table would live there so you could share them with your players (and let them roll). 

The way tables are implemented now works. Coming from 5e, I've just never seen it done this way before. I could obviously create them all manually, if I really hated myself enough.

**Comment by moo-man** [comment]
Originally it was because Foundry's "Rollable Tables" didn't exist and I had to come up with something. Now, I just sorta prefer it this way, as i've built in a lot of functionality specific to WFRP, like multi-columned tables (e.g. weather and career). To me it's a smoother experience (I've never liked how Foundry's table links open the table menu, instead of just rolling on the table), and it's not as easy to apply a modifier to the roll in Foundry's tables without going in and editing the table formula.

I'm not sure what you mean by the events table. Players can roll on tables just the same as GMs can.

**Comment by gravagehulk** [comment]
Nothing wrong, per se. I actually like your implementation. Like I said, I guess it's just different, coming from other systems. Thanks for the feedback.
