### ISSUE TITLE
[WFRP4e Core] Cannot add career to NPC

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#387]
Hi,

I cannot add a career to any NPC I create after I create the Actor.

I drag and drop it from the Items Tab but nothing happens. 
Everything is up to date as far as I know.

Regards,
Aris<br/>**From**: ArisKrik<br/>wfrp4e: 3.3.3<br/>wfrp4e-core: 1.3.0<br/>wfrp4e-rnhd: 1.4.0<br/>wfrp4e-starter-set: 1.4.0

**Comment by moo-man** [comment]
Could not reproduce, need more details, please contact me on discord Moo Man#7518 to more easily troubleshoot

**Comment by mlilge** [comment]
Same here! Since the update to 1.3.1 I also experience issues when dragging more than one career into a NPC sheet:

1) Create a vanilla NPC
2) Drag more than one career from the compendium into the sheet, e.g. Physican lvl 1-3
3) Close the sheet and reopen it from the actor's directory
4) try to mark lvl1 career completed - doesn't work
5) close sheet again but it won't reopen from the directory again, nor from a token. One would have to delete the NPC.

I noticed a couple of more issues with this flow, e.g. one won't be able to tick mark careers completed after step #2.

**Comment by moo-man** [comment]
Can you verify what system version you are on? I would hope it's not really 1.3.1

**Comment by mlilge** [comment]
It's v1.3.1 for the core content Module and v3.3.3 for the system.

**Comment by mlilge** [comment]
Same issue when trying to add more than one talent in one go.

**Comment by moo-man** [comment]
I cannot reproduce this in 3.4.1, try updating and then test it again.

**Comment by mlilge** [comment]
Wasn't aware of the system update.

Just reading the heads up message. Is it safe to migrate from 3.3.3 to 3.4.1 despite having already installed core v1.3.1 or shall I better fall back to v1.3.0?

**Comment by moo-man** [comment]
It is fine, ideal even. Everything past 1.3.0 is good to migrate from.

**Comment by moo-man** [comment]
BUT STILL BACK UP :)

**Comment by mlilge** [comment]
After the upgrade it's looking fine for me. Issue resolved. Many thanks for your swift support!

**Comment by moo-man** [comment]
Good to hear 👍
