### ISSUE TITLE
[WFRP4e Core] wfrp4e tables

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#495]
There is are two "Random Eye Colour" tables, the second looks like it should be "Random Hair Colour"

Looks like a simple label change is required.<br/>**From**: monicle<br/>wfrp4e: 3.5.0<br/>wfrp4e-core: 1.3.2<br/>wfrp4e-eis: 1.2.2<br/>wfrp4e-rnhd: 1.4.1<br/>wfrp4e-starter-set: 1.4.2<br/>wfrp4e-ua1: 1.0.2

**Comment by simulacrum-1** [comment]
It's the Ogre module. He's hitched on to your /char system to add Ogres and copied your old RNHD hair table with eye colour name you fixed in the last update.
<img width="726" alt="Screenshot 2021-04-03 at 18 26 32" src="https://user-images.githubusercontent.com/68729767/113486398-64b70800-94aa-11eb-9111-e699eb1940a6.png">
