### ISSUE TITLE
[WFRP System] Add another entity permission, something between observer and owner, to the actors

### ISSUE THREAD

**Issue by szygin** [moo-man/WFRP4e-FoundryVTT#837]
I don't trust my players much, but I'd like them to have possibility to do basic changes in their character sheets like spending money for items, shooting bows or testing skills. It's not possible with 'observer', but 'owner' could let them to cheat.

**Comment by moo-man** [comment]
Adding entity permissions isn't really within the scope of the system. Those are defined by Foundry and even if I had a mind to, I probably couldn't due to database validation only accepting the defined values.

Additionally, I don't believe adding this will really solve the issue, no amount of code will really solve what is ultimately a "people problem."
