### ISSUE TITLE
[WFRP4e System] Sidebar too narrow for clearly displaying system version

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#874]
The sidebar width has reduced from 456px to 392px in a recent release (https://github.com/moo-man/WFRP4e-FoundryVTT/commit/84cf717d40201598782ea0b179fe676a0de1acdb)
This forces the system version to drop to the next line and appear to concatenate with the active modules count. 
The change happens at 410px or less. <br/>**From**: Jagusti#3610<br/>wfrp4e: 4.2.1<br/>wfrp4e-archives1: 2.1.1<br/>wfrp4e-core: 2.1.2<br/>wfrp4e-dotr: 2.0.6<br/>wfrp4e-eis: 2.0.5<br/>wfrp4e-middenheim: 2.1.2<br/>wfrp4e-rnhd: 2.1.2<br/>wfrp4e-starter-set: 2.0.3<br/>wfrp4e-ua1: 2.0.2

**Comment by Jagusti** [comment]
At 410px or less
![image](https://user-images.githubusercontent.com/521096/135865080-aa701a66-6574-4b1d-8d16-c9be9ded24fc.png)

At >410px (eg 456px), there is still a bit of a gap to the right margin for the system version.
![image](https://user-images.githubusercontent.com/521096/135865684-fb11c9cc-64fb-43a8-b3c4-e0823f2b5ed3.png)


If the `font-size` for `#sidebar #settings ul` (wfrp4e.css:1964) is unset or inherited rather than fixed at 16x, this appears acceptable without expanding the sidebar again (though a little smaller):
![image](https://user-images.githubusercontent.com/521096/135865918-394d5514-8e93-40d1-98e0-fd04050239ad.png)

**Comment by moo-man** [comment]
I think this went unnoticed because without the new foundry version indicator, it's fine.
