### ISSUE TITLE
[Archives of the Empire: Vol 1.] Cannot roll for career when Archives module is activated

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#908]
Rolling for a career in the character generation process works as expected with Core Content module + any of the premium content modules, apart from Archives 1. No other modules are set up / installed when the folowing error is returned in console:

tables-wfrp4e.js:114 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Function._inRange (tables-wfrp4e.js:114)
    at Function._lookup (tables-wfrp4e.js:99)
    at Function.rollTable (tables-wfrp4e.js:74)
    at GeneratorWfrp4e.rollCareer (char-gen.js:206)
    at Function._onCharGenButtonClick (chat-wfrp4e.js:303)
    at HTMLElement.dispatch (jquery.min.js:2)
    at HTMLElement.v.handle (jquery.min.js:2)<br/>**From**: Jagusti#3610<br/>wfrp4e: 4.2.1<br/>wfrp4e-archives1: 2.1.1<br/>wfrp4e-core: 2.1.2

**Comment by Jagusti** [comment]
I still get this on a brand new world running WFRP4e 4.3.0 on FVTT 0.8.9 and only the Core 2.2.0 and Archives 2.2.0 modules activated and initialised. 
![image](https://user-images.githubusercontent.com/521096/143463862-044580db-7b76-4a4b-8d7c-692235271d45.png)

In a different environment with WFRP4e 4.3.0 on FVTT 0.8.9 and only the Core 2.2.0 module activated, I get this. If I try and run character creation when this error appears, I get the same error as above when rolling for career.
![image](https://user-images.githubusercontent.com/521096/143471423-4385e57a-9cce-4b81-aae1-45c9d490d9f1.png)

Cold this be related to [changes introduced in 4.1.0](https://github.com/moo-man/WFRP4e-FoundryVTT/releases/tag/4.1.0)? I don't remember running chargen after upgrading to 4.1.0 until recently, so not really sure when the error started appearing. 
![image](https://user-images.githubusercontent.com/521096/143471948-272a59a3-da8a-43d7-9268-d58590555baa.png)

**Comment by moo-man** [comment]
Yeah so that change would probably cause those errors, but I have no idea why you wouldn't have the updated tables. Does your career.json table define `multi` instead of `columns`?

**Comment by Jagusti** [comment]
It does define `multi`, right at the end after the rows. Makes no difference if I move it up the file of course. (I've added the .txt extension to the attached to post here, otherwise it's the same file as in the module.)
[career.json.txt](https://github.com/moo-man/WFRP4e-FoundryVTT/files/7604923/career.json.txt)

**Comment by Jagusti** [comment]
Turns out this error only appears when selecting `Default` as the Subspecies for a Human to generate attributes and then selecting a career. If I choose `Reiklander` (or `Middenlander`, etc) it kicks out a career as expected.  If I select `Default` for another race, that also gives a career as expected.
