### ISSUE TITLE
[WFRP4e System] Character Portrait Trouble

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#961]
Moo man, this is an extremely remarkable systems and I give you immense props for how great it is. I'm currently struggling to add character portraits to the character sheets. The Token configuration says that upload has been disabled and when I try to copy/paste a path to an image on my laptop it just defaults to the hooded head image. Any ideas for fixes?<br/>**From**: nretseloc@gmail.com<br/>wfrp4e: 5.0.3<br/>wfrp4e-core: 2.3.2<br/>wfrp4e-rnhd: 2.3.1

**Comment by Vendare** [comment]
You can't upload into the default token directory. Due to the default token residing in that folder foundry is pointing you towards it. This is a game system folder you can't use these folders for uploading user data
![image](https://user-images.githubusercontent.com/6638899/147415733-a69a8cff-4e5a-4e39-84f9-0c3a162b2738.png)
You have to navigate into the topmost directory and upload your files directly or create a new folder here to to put your files into
![image](https://user-images.githubusercontent.com/6638899/147415808-69a8708a-3de3-4927-b82f-d1df2c6bb02e.png)
